name: CI/CD - Lista de Compras Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install

      - name: Executar Testes
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy para Render
        run: echo "Configurar Deploy no Render" # Será configurado no próximo passo
